# Generated by Django 3.2.3 on 2021-07-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={},
        ),
        migrations.AlterModelOptions(
            name="course",
            options={},
        ),
        migrations.AlterModelOptions(
            name="section",
            options={},
        ),
        migrations.AlterModelOptions(
            name="site",
            options={},
        ),
    ]
